### ISSUE TITLE
MDIO documentation improvement 

### ISSUE THREAD

**Issue by jzygeorgia** [TGSAI/mdio-python#110]
In the MDIO documentation, in the explanation CLI Reference about the chunks (below), maybe improve the documentation (e.g. put a period "." between "2-byte" and "Chunks") ? 

3D Seismic Shot Data (Byte Locations Vary): Let’s assume streamer number is at byte 213 as 2-bytes Chunks: 8 shots x 2 cables x 256 channels x 512 samples –header-locations 9,213,13 –header-names shot,cable,chan –header-lengths 4,2,4,4 –chunk-size 8,2,256,512

**Comment by jzygeorgia** [comment]
also in the documentation below,  header-lengths should be "4,2,4"  instead of "4,2,4,4" ? 

header-names shot,cable,chan –header-lengths 4,2,4,4

**Comment by tasansal** [comment]
closed by #118
