### ISSUE TITLE
Add "timezone" mdio "created" date

### ISSUE THREAD

**Issue by blasscoc** [TGSAI/mdio-python#114]
mdio data has a "create" field in it's "zattrs" file. 

The propose feature would add time zone information to this datetime in some canonical way.

In a scenario where timezone information is unavailable; the meta data should record that it does not have that information; and not default to something like UTC.

**Comment by tasansal** [comment]
Good point. I think one clean way to standardize it would be to always save it as UTC and define it as a part of the standard to avoid time zone confusion. Then it's up to the client library to decide what to do with that information.

**Comment by blasscoc** [comment]
@tasansal thanks for the quick reply. Yes; since there likely isn't a large backlog of mdio data _yet_, having that requirement would save some trouble in the future.
