### ISSUE TITLE
Feature request - add Python 3.11 support 

### ISSUE THREAD

**Issue by blasscoc** [TGSAI/mdio-python#116]
They current mdio project toml limits the Python version:

python = ">=3.8,<3.11"

Now that Python 3.11 has been release, the new feature would add support for it.

**Comment by tasansal** [comment]
Yup! We need to wait till Numba supports 3.11

https://github.com/numba/numba/milestone/63

**Comment by tasansal** [comment]
https://github.com/numba/numba/issues/8304
