### ISSUE TITLE
Synchronization for `MDIOWriter`

### ISSUE THREAD

**Issue by srib** [TGSAI/mdio-python#121]
Currently, [`MDIOWriter`](https://mdio-python.readthedocs.io/en/stable/reference.html#mdio.api.accessor.MDIOWriter) does not have ability to control synchronization anyway. It is extraneous to the `MDIOWriter` class.

I think `MDIOWriter` is useful if it has ability to expose synchronization for users. I don't know what form it takes but I am currently having a use case where I am having to calculate it to align with the chunk boundaries. This can perhaps be made simple enough for users?

What do you think?

cc @tasansal

**Comment by tasansal** [comment]
Currently, we only recommend chunk-aligned writes. Synchronization can be done via the Dask scheduler as well using the Dask backend.
