### ISSUE TITLE
Add an ability to pass a dask client to `MDIOReader`

### ISSUE THREAD

**Issue by srib** [TGSAI/mdio-python#243]
@markspec thinks that it might be a useful idea to have the ability to pass a `Client` to `MDIOReader`.

**Comment by tasansal** [comment]
Not sure if this makes sense. The client is used at the Dask Distributed `.compute()` or `.persist()` calls which is a downstream application than MDIO. MDIO makes no such calls it only returns lazy arrays.

@markspec can you elaborate?

**Comment by markspec** [comment]
@tasansal, makes sense.  Let's close.
