### ISSUE TITLE
header scan fails incorrect for little endian segy

### ISSUE THREAD

**Issue by anthonytorlucci** [TGSAI/mdio-python#258]
In segyio, the `buf` is ALWAYS big endian regardless of the segy bytorder. Thus, `def header_scan_worker()` will result in incorrect header values for the snippet below from `src/mdio/segy/_workers.py`:

```python
formats = [type_.numpy_dtype.newbyteorder(endian) for type_ in byte_types]
```

An issue was raised with [segyio issues #559](https://github.com/equinor/segyio/issues/559). Confirmed in discussion on Slack.

Example of behavior can be found at [anthonytorlucci/segyio_header_buf](https://github.com/anthonytorlucci/segyio_header_buf).

**Comment by tasansal** [comment]
Thanks for raising the issue. We will take a look before the next release.

**Comment by anthonytorlucci** [comment]
I believe the fix is very simple (line 86 in `/src/mdio/segy/_workers.py`)

```python
formats = [type_.numpy_dtype.newbyteorder('>') for type_ in byte_types]
```

since the byte order in `buf` is always BIG.

I forked the project, but unable to run `nox` without errors so I haven't submitted a pull request.

**Comment by tasansal** [comment]
@anthonytorlucci I made the fix and its on the main branch. Can you test it either:

1. test pypi: https://test.pypi.org/project/multidimio/
2. clone main and install locally

Thanks
