### ISSUE TITLE
Sparsity check override

### ISSUE THREAD

**Issue by cable34** [TGSAI/mdio-python#284]
Sometimes users need ability to run very sparse grids. 

Disable the sparity check/warning  with extra option.

In some cases, there can be duplicate 0s in a segy that cause an error/warning to be displayed and the mdio ingestion fails. 
Can provide user with a waring but still ingest the segy to mdio.

**Comment by tasansal** [comment]
This should ideally be done via an environment variable, for whoever implements it.

**Comment by markspec** [comment]
@cable34 @tasansal, How about MDIO_IGNORE_CHECKS=True?
