### ISSUE TITLE
Reduce memory requirements for segy cutting 

### ISSUE THREAD

**Issue by markspec** [TGSAI/mdio-python#298]
mdio_to_segy requires a significant amount of memory for large datasets.  This seems related to https://github.com/dask/dask/pull/10535

Test dask release: 2023.10.0

**Comment by fjetter** [comment]
Is it possible to have a minimal reproducer for this memory increase? Note that we just merged another change to the relevant code sections, see https://github.com/dask/dask/pull/10660 which I hope may be more stable. I would still be interested in a reproducer for your problem

**Comment by markspec** [comment]
@fjetter , thanks for the interest.  I'll close this issue as bumping to dask >=2023.10.0 has resolved this.
