### ISSUE TITLE
MDIO copy is slow

### ISSUE THREAD

**Issue by cable34** [TGSAI/mdio-python#309]
mdio copy function is very slow. It starts the copy but nothing happens for a long time on the cpu. Need to profile.

**Comment by tasansal** [comment]
Hey @cable34, thanks for the report. We rely on Zarr's logic to copy from store to store. Before we can diagnose further, can you please provide more information:
* Python version
* Version of MDIO
* Source hardware/cloud store
* Destination hardware/store
* How you initiate the copy
* What are the numbers you are getting, and what is the expectation?

**Comment by tasansal** [comment]
@cable34 I am going to close this issue since it's been stale since November. If it's still a problem please open another one and answer the above questions. Thanks.
