### ISSUE TITLE
Improve logging for autochannelwrap

### ISSUE THREAD

**Issue by markspec** [TGSAI/mdio-python#331]
Improve logging to let users know the reason for sparse grid and take self-corrective action on whether to ingest with autoindex or autochannelwrap.

This has become an issue for streamer data where ingestion with autochannelwrap usually works.  In the unusual case of unwrapped channels with duplicate traces then segy2mdio ingestion will fail with a sparse index error.  In this case the user would like to see an what the first repeated channel was to aid diagnosis and a suggestion to use autoindex in the case that the job fails.

**Comment by tasansal** [comment]
💯 for improving logging.

I would be against taking self-corrective action by the code. It makes it unpredictable.

**Comment by tasansal** [comment]
merged pr, closing.
