### ISSUE TITLE
Colab and Binder badge for notebooks

### ISSUE THREAD

**Issue by srib** [TGSAI/mdio-python#49]
I think it is a good idea to have a Colab and/or Binder badge for the tutorial notebooks.

[Here](https://github.com/marketplace/actions/colab-badge-action) is an action on the GitHub marketplace.

**Comment by tasansal** [comment]
We should also add Amazon SageMaker Studio Lab. Equivalent to Colab etc on AWS side.

https://aws.amazon.com/sagemaker/studio-lab/

**Comment by YB-24** [comment]
I want to contribute in this project, Can you please assign this issue to me.

**Comment by srib** [comment]
@YB-24 Thanks for checking this project out! Please make a pull request and someone will offer feedback if needed.
