### ISSUE TITLE
Resolve issue with EBCDIC header of SEGY created by Petrel

### ISSUE THREAD

**Issue by gmac161** [TGSAI/mdio-python#50]
OS windows10; python 3.9; MDIO v0.1.6

SEGY files generated by Petrel crash with an error related to the EBCDIC.

----------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In [14], line 1
----> 1 segy_to_mdio(
      2     segy_path=f,
      3     mdio_path_or_buffer="tst3d_cube.mdio",
      4     index_bytes=(5, 9),
      5     index_names=("inline", "crossline"),
      6 )

File C:\appl\python\env\mdio_tst\lib\site-packages\mdio\converters\segy.py:173, in segy_to_mdio(segy_path, mdio_path_or_buffer, index_bytes, index_names, index_lengths, chunksize, endian, lossless, compression_tolerance, storage_options, overwrite)
    169 # Read file specific metadata, build grid, and live trace mask.
    170 with segyio.open(
    171     filename=segy_path, mode="r", ignore_geometry=True, endian=endian
    172 ) as segy_handle:
--> 173     text_header = parse_text_header(segy_handle)
    174     binary_header = parse_binary_header(segy_handle)
    175     num_traces = segy_handle.tracecount

File C:\appl\python\env\mdio_tst\lib\site-packages\mdio\segy\parsers.py:66, in parse_text_header(segy_handle)
     54 def parse_text_header(segy_handle: segyio.SegyFile) -> list[str]:
     55     """Parse text header from `bytearray` to python `list` of `str` per line.
     56 
     57     The `segyio` library returns the text header as a  `bytearray` instance.
   (...)
     64         Parsed text header in list with lines as elements.
     65     """
---> 66     text_header = segy_handle.text[0].decode()
     67     text_header = [
     68         text_header[char_idx : char_idx + 80]
     69         for char_idx in range(0, len(text_header), 80)
     70     ]
     71     return text_header

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 155: invalid continuation byte

--------- 

Petrel EBCDIC appear to require encoding='ISO-8859-1' rather than the default UTF-8

Using 
**_segy_handle.text[0].decode(errors='ignore')_**
should get around this issue

**Comment by srib** [comment]
Thank you for reporting this issue, @gmac161.

Would you mind sending a PR? If not, will push a fix soon.

**Comment by tasansal** [comment]
@gmac161, thanks for reporting it. I fixed it in #51 

Can you please try it from that branch and let us know if it resolved the issue?

If you are using GitHub CLI

```shell
git clone https://github.com/TGSAI/mdio-python.git
gh pr checkout 50
pip install -e .
```

**Comment by gmac161** [comment]
@tasansal I've run my cube using this branch and it works

**Comment by tasansal** [comment]
@gmac161, thank you very much for your feedback and testing! I will close the issue.
