### ISSUE TITLE
GPU direct storage backend for mdio

### ISSUE THREAD

**Issue by srib** [TGSAI/mdio-python#64]
We should perhaps consider having a GPU Direct Storage backend for mdio. `kvikio.zarr.GDSStore` enables it available through [`kvikio`](https://docs.rapids.ai/api/kvikio/stable/api.html#kvikio.zarr.GDSStore).

Some relevant links here: 

https://github.com/xarray-contrib/xbatcher/issues/87

https://github.com/zarr-developers/zarr-python/pull/934

https://zarr.readthedocs.io/en/stable/release.html#release-2-13-0

https://github.com/pydata/xarray/pull/6874

**Comment by tasansal** [comment]
Not planned at the moment.
